modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="a_whole_new_perspective"
version="2.5.3-indev"
displayName="The Vesuvius Project"
credits="Made possible by: MCreator, Zapsplat and myself"
displayURL="https://mcreator.net"
authors="AJ, MCreator"

[[dependencies.a_whole_new_perspective]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




